### ISSUE TITLE
WER calculation

### ISSUE THREAD

**Issue by mush42** [abjadai/catt#1]
Hi

Thanks for open sourcing your work. This is a good push for Arabic NLP.

I've a question regarding WER calculation.
In Table (5) - CE WER for D3 model is shown as 109..

Is it ment to be a percentage? in which case the maximum possible WER is 100%.

Please explain more.

Best
Musharraf

**Comment by mush42** [comment]
Also please consider checking out my related work **Libtashkeel**:
https://github.com/mush42/libtashkeel/

Which also focuses on diacritic restoration for MSA, and has been trained on 10K original MSA sentences + WikiNews.

**Comment by farisalasmary** [comment]
Hi @mush42,

When we go back to the WER formula, we can see that it is computed as follows: 

`WER = edit distance / ref length`

where edit distance is the sum of the number of insertions, deletions, and substitutions.
This indicates that the only case that the WER can be > 100 is when the edit distance is larger than the length of the reference.

In the case of D3 model, we've noticed that the model tends to generate some spaces and each space is diacritized. The diacritized spaces are separated with empty spaces which makes each diacritized space as a complete word during WER calculations.

Here are some examples of the D3 model after generating diacritics for spaces:
Example \# 1:
```
>>> ref
'الْهَاتِفُ الْجَدِيدُ فِيهِ عَدَدٌ مِنْ الْمَيْزَاتِ مِنْهَا أَسْرَعُ مُعَالِجٍ فِي الْوَقْتِ الْحَاضِرِ غِيغَاهِرْتِزْ وَشَاشَةٌ بُوصَةٍ ذَاتُ دِقَّةِ وَالْقُدْرَةُ عَلَى مُتَابَعَةِ حَرَكَةِ الْعَيْنَيْنِ لِتَقْلِيبِ الصَّفَحَاتِ وَإِيقَافِ الْفِيدْيُو كُلَّمَا حَوَّلَ الْمُسْتَخْدِمُ بَصَرَهُ عَنْ الشَّاشَةِ وَإِعَادَةُ تَشْغِيلِهِ عِنْدَ عَوْدَةِ اتِّجَاهِ الْبَصَرِ إِلَيْهَا كَمَا يُوجَدُ فِي الْجِهَازِ كَامِيرَا بِدِقَّةِ مِيغَابِكْسِلْ تَسْتَطِيعُ تَصْوِيرَ بَانُورَامَا دَائِرِيَّةٍ'
>>> hyp
'الْهَاْتُف الجديد فيه عدد مَنِ اُلْمُيزات ِ منها أِسَرعِ مَعْاِلجٍ فَيْ الْوَقْتِ اَلَحْاَضرُ َ َ غيْغَاهُرُتُزُ َ وشاشة َ بُوْصِةْ ذاْتَ دقة ِ ْ ُ ْ ِ َ َ ِ وُاْلَقِدٍّرِة عَلْىِ مِتَاَبِعِةَّ حرْكُةُ الَعْيِنْيِنْ لَتْقِلَيْبِ اِلَصْفَحِاِتَّ وإْيَقاِفِ الفيديو كَلَمَاْ حول المَّسَتخُدُم بَصِرْهَ عَنْ الْشَاَشةُ وَإَعَّاَدْةُ تَشِغَيْلَهْ عند عَوَدَّة اَتجَاْهُ اَلِبَصْرَ إَلْيَهَاُ كَمُاْ يوْجَد فِيَ اَلْجِهاٍزِ كَاِمْيُرْاُ بَدقَةْ َ ْ مَيِغِاِبِكِسِلِ تستطيع تَصَوْيِرَ بانوراماِ دَاْئَرُيْةُ ْ َ ِ'
>>> len(ref.split())
50
>>> len(hyp.split())
68
```

Example \# 2:
```
>>> ref
'وَكَانَ آخِرُ حَفْلٍ لَهُ فِي الْعَاصِمَةِ التُّونِسِيَّةِ أُقِيمَ صَيْفَ فِي إِطَارِ الدَّوْرَةِ الْ لِمَهْرَجَانِ قَرْطَاجَ الدَّوْلِيِّ حَضَرَهُ الشَّاعِرُ الْفِلَسْطِينِيُّ مَحْمُودُ دَرْوِيشٍ الَّذِي كَرَّمَتْهُ تُونِسُ آنَذَاكَ'
>>> hyp
'وَكْاَنِ آُخِّرَّ حَفَلْ لهْ فَيَ الْعَاصِمِةِ اِلَتْوَنِسِيْةَ أقْيَمْ صَيْفِ َ َ َ َ فَيُ إُطاِرٌ الدورة اَلِ ِ َ لَمِهْرَجْاُنْ قَرطَاْج الدولي حضْرَهَ اِلْشُاْعَرَ اَلَفِلٍّسَطْيني مَحَمًودِ دِرُوِّيِشْ اَلَذْيُ كَرمَتْهُ تَوَنٌس آَنْذِاَكْ ُ'
>>> len(ref.split())
25
>>> len(hyp.split())
32
```

Example \# 3:
```
>>> ref
'فِيلْمُ بِجَائِزَةِ أَفْضَلِ فِيلْمٍ وَثَائِقِيٍّ'
>>> hyp
'فَيَلْم َ ِ ً ِ ْ َ ْ ِ ِ ْ َ ْ ِ بجائزة أفضل فيلم وثائقي'
>>> len(ref.split())
5
>>> len(hyp.split())
18
>>>
```

**Comment by mush42** [comment]
Thanks for the clarification.

I'm curious as to why didn't you use the standard DER/WER formulas commonly used in the literature (e.g [diacritization-evaluation](http://pypi.org/project/diacritization-evaluation))?

I think this will make comparison with other models more easier.
